name: Docker Build -> Push -> Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Build Jar
      run: ./mvnw clean package -DskipTests

    - name: Login to Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-demo-ci-demo:latest

    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-demo-ci-demo:latest

    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: "foo.com:1234,bar.com:5678"
        username: ${{ secrets.EC2_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop spring-demo || true
          docker rm spring-demo || true
          docker pull  ${{ secrets.DOCKER_USERNAME }}/springboot-demo-ci-demo:latest
          docker run -d --name spring-demo -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/springboot-demo-ci-demo:latest
    
    
